### ISSUE TITLE
Add support for Catena 4630, 4617 and 4618

### ISSUE THREAD

**Issue by dhineshkumarmcci** [mcci-catena/Catena-Arduino-Platform#135]
Need to add platform support for Catena 4630.

**Comment by dhineshkumarmcci** [comment]
Added support for Catena 4630 under branch [issue135](https://github.com/mcci-catena/Catena-Arduino-Platform/tree/issue135).

**Comment by terrillmoore** [comment]
Don't forget that you must add entries to .travis.yml here, and in the other libraries (arduino-lmic and arduino-lorawan), to confirm that the libraries compile with the BSP.

**Comment by dhineshkumarmcci** [comment]
Also added to add support for Catena 4617 and 4618 ( issue #173 ) in this push.
