### ISSUE TITLE
Catena4551m101~104 is set up as Catena4550 during provisioning

### ISSUE THREAD

**Issue by sjpark-mcci** [mcci-catena/Catena-Arduino-Platform#27]
After giving a command "system configure platformguid xxx...xxx" during provisioning Catena4551m101~104, the platformguid is always switched to Catena4550 platformguid. This is because in "src/lib/stm32/catena455x/Catena455x_GetPlatformForID.cpp", m101 ~104 is not added in CATENA_PLATFORM(); chooses the default which is Catena4550.

const CATENA_PLATFORM (* const Catena455x::vPlatforms[]) =
	{
	// entry 0 is the default
	&gkPlatformCatena4550,
	&gkPlatformCatena4551,
	};

To fix this, m101~104 need to be added in the above code and also in the header file. Similar bugs were found with samd code. The following files need to be fixed.

src/Catena_Platforms.h
- need to add Catena4551m101~104
src/lib/samd/catena4450/Catena4450_GetPlatformForID.cpp
- need to add Catena4450m103~104
src/lib/samd/catena4460/Catena4460_GetPlatformForID.cpp
- need to add Catena4460m103~104
src/lib/stm32/catena455x/Catena455x_GetPlatformForID.cpp
- need to add Catena4551m101~104

**Comment by terrillmoore** [comment]
Is there anything for me to review? Have we created a pull request?

**Comment by terrillmoore** [comment]
Changes are made on my side, doing test compiles.
