### ISSUE TITLE
Make CatenaRTC class portable

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/Catena-Arduino-Platform#61]
Right now, CatenaRTC will only compile on SAMD21 ports. It would be easy to refactor a little and make this portable. SAMD21 can use the RTCzero as a base (without making methods public) and STM32 can use whatever makes sense in our library, mapping the sleep constants onto the useful things from <CatenaStm32L0Rtc.h>

**Comment by terrillmoore** [comment]
@chwon64 -- can we close this?

**Comment by chwon64** [comment]
Yes, we can close it.
