### ISSUE TITLE
Many CatenaXYZs have m_pPlatform pointers

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/Catena-Arduino-Platform#98]
If you trace through the chain of inheritance, you will find the following.

`private CatenaSamd21::m_pPlatform` exists, but is overridden by `protected CatenaFeatherM0::m_pPlatform`

Similarly,  `private CatenaStm32::m_pPlatform` exists, but is overridden by `protected CatenaStm32L0::m_pPlatform`.

There should not be two things with one name, this is very confusing! And anyway, we should be able eto get away with a single variant.

**Comment by chwon64** [comment]
This is fixed as part of #65.
